export enum ActionType {
  SEND_REQUEST = "SEND_REQUEST",
  REQUEST_RETURNED = "REQUEST_RETURNED",
  REQUEST_FAILED = "REQUEST_FAILED",
  SELECT_TEMPLATE = "SELECT_TEMPLATE",
  ADD_NEW_TEMPLATE = "ADD_NEW_TEMPLATE",
  UPDATE_TEMPLATE = "UPDATE_TEMPLATE",
  START_THE_TRAIN = "START_THE_TRAIN"
}
