export enum ActionType {
  SEND_REQUEST = "SEND_REQUEST",
  REQUEST_RETURNED = "REQUEST_RETURNED",
  REQUEST_FAILED = "REQUEST_FAILED",
  SELECT_TEMPLATE = "SELECT_TEMPLATE",
  ADD_NEW_TEMPLATE = "ADD_NEW_TEMPLATE"
}
